Controllers/ProductTypeController.cs
using EcommerceProject.Models;
using EcommerceProject.Repository;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceProject.Controllers
{
    public class ProductTypeController: Controller
    {
        IprodutTypeRepository ProductTypeRepo;
        public ProductTypeController(IprodutTypeRepository _ProductTypeRepo)//inject
        {
            ProductTypeRepo= _ProductTypeRepo;

        }
       public IActionResult Index()
        {
            
            return View(ProductTypeRepo.GetAll());
            
        }
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult New(ProductType productType)
        {
            if(ModelState.IsValid) 
            {
                TempData["Save"] = "Product Type has been Saved  ";
                ProductTypeRepo.Insert(productType);
                return RedirectToAction("Index");
            }
            return View(productType);
        }
        
        public IActionResult Delete(int id)
        {
            
            return View(ProductTypeRepo.GetById(id));
        }
        public IActionResult FinalDelete(int id)
        {
           ProductTypeRepo.Delete(id);
           return RedirectToAction("Index");  
        }
        public IActionResult Edit(int id)
        {
            
            return View(ProductTypeRepo.GetById(id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,ProductType productType)
        {
            if(ModelState.IsValid)
            {
                TempData["edit"] = "Product Type has been Edited";
                ProductTypeRepo.Update(id,productType);
                return RedirectToAction("Index");
            }
            return View(productType);
        }
    }
}

Views/ProductType/Delete.cshtml
@model ProductType
<div class=" row">
    <div class="col-12 text-info mt-5 ">
        <h2>Delete Product Type</h2>
    </div>
    <form style="border-style: ridge;">
        <div class="form-group row">
            <div class="col-2 mt-4">
            <label asp-for="ProductTypeName" class="form-label"></label>
            </div>
            <div class="col-5 mt-4">
                <input asp-for="ProductTypeName" class="form-control ">
            </div>
          <div class="mt-4 mb-4">
                <a href="/ProductType/FinalDelete/@Model.Id"   class="btn btn-primary">Delete</a>
                <a asp-action="Index" asp-controller="ProductType" class="btn btn-success"> Back To List</a>
          </div>
        </div>
    </form>
</div

Views/ProductType/Edit.cshtml
@model ProductType
<div class=" row">
    <div class="col-12 text-info mt-5 ">
        <h2>Edit Product Type</h2>
    </div>
    <form asp-action="Edit" method="post" style="border-style: ridge;">
        <div class="form-group row">
            <div class="col-2 mt-4">
            <label asp-for="ProductTypeName" class="form-label"></label>
            </div>
            <div class="col-5 mt-4">
                <input asp-for="ProductTypeName" class="form-control ">
            </div>
          <span asp-validation-for="ProductTypeName" class="text-danger"></span>
          <div class="mt-4 mb-4">
                <button type="submit" class="btn btn-primary">Update</button>
                <a asp-action="Index" asp-controller="ProductType" class="btn btn-success"> Back To List</a>
          </div>
        </div>
    </form>
</div
@section Scripts
{
    <partial name="_ValidationScriptsPartial"></partial>
}

Views/ProductType/Index.cshtml
@model List<ProductType>
<br />
<div class="row ">
    <div class="col-6">
        <h2 class="text-info">Product Type List</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-action="New" class="btn btn-info text-white fw-bold" >
            <i class="fa fa-plus" style="font-size:1.2rem;color:white"></i>
            New Product Type
        </a>
    </div>
</div>
<br />
<div>
    <table class="table table-striped border">
        <tr class="table-info">
            <th>
                Product Type
            </th>
            <th></th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.ProductTypeName</td>
                <td class="text-end">
                    <a href="/ProductType/Edit/@item.Id" class="btn btn-primary">
                        <i class='fas fa-edit' style='font-size:1.4rem'></i>
                    </a>
                    <a href="/ProductType/Delete/@item.Id" class="btn btn-danger">
                        <i class='far fa-trash-alt' style='font-size:1.4rem'></i>
                    </a>
                </td>
            </tr>
        }
    </table>
</div>
@section Scripts
{
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <script>
        $(function(){
            var save = '@TempData["Save"]';
            var edit = '@TempData["edit"]';
            if(save!=null)
            {
                alertify.success(save);
            }
           if (edit != null) {
                alertify.success(edit);
            }
        })

    </script>
}

Views/ProductType/New.cshtml
@model ProductType
<div class=" row">
    <div class="col-12 text-info mt-5 ">
        <h2>Add New Product Type</h2>
    </div>
    <form asp-action="New" method="post" style="border-style: ridge;">
        <div class="form-group row">
            <div class="col-2 mt-4">
            <label asp-for="ProductTypeName" class="form-label"></label>
            </div>
            <div class="col-5 mt-4">
                <input asp-for="ProductTypeName" class="form-control ">
            </div>
            <span asp-validation-for="ProductTypeName" class="text-danger"></span>
          
          <div class="mt-4 mb-4">
                <button type="submit" class="btn btn-primary">Add</button>
                <a asp-action="Index" asp-controller="ProductType" class="btn btn-success"> Back To List</a>
          </div>
        </div>
    </form>
</div>
@section Scripts
{
    <partial name="_ValidationScriptsPartial"></partial>
}